#ifndef AMREX_FABARRAY_UTILITY_H_
#define AMREX_FABARRAY_UTILITY_H_
#include <AMReX_Config.H>

#include <AMReX_FabArray.H>
#include <AMReX_LayoutData.H>
#include <AMReX_Print.H>
#include <limits>

// Four sets of utilities - spread out into four files because of excessive size
#include <AMReX_FabArrayUtility_Sum.H>
#include <AMReX_FabArrayUtility_Min.H>
#include <AMReX_FabArrayUtility_Max.H>
#include <AMReX_FabArrayUtility_Ops.H>

#endif